### PR TITLE
Migrating from React.PropTypes

### PR DESCRIPTION
**Pull request by Odrin**
Fix React [deprecation warning](https://facebook.github.io/react/blog/#migrating-from-react.proptypes).

### CODE REVIEW

**Comment by travi** [comment]
@gaearon anything you can do to nudge this internally? this is the last package preventing the react 15.5 upgrade on a few projects for my team

**Comment by gaearon** [comment]
Sure thing.

**Comment by travi** [comment]
Great, thanks!

**Comment by gaearon** [comment]
@kyldvs will review this soon.

**Comment by kyldvs** [comment]
I think this is okay - really I have no idea how this repo works though :)

**Comment by gaearon** [comment]
Can you get a patch release out?

**Comment by wcjordan** [comment]
Hey @kyldvs & @gaearon, I'm one of the maintainers of the [fixed-data-table-2 fork](https://github.com/schrodinger/fixed-data-table-2).  You should be able to create a release with `npm run publish-package`.  We ran into some issues because react-docgen doesn't support create-react-class yet, but I'm working on a [PR for that](https://github.com/reactjs/react-docgen/pull/179).

While you're active here, would it be possible to revisit adding a deprecation notice to the repo that points users to fixed-data-table-2 and react-virtualized?  It's been discussed for a while, but the repo's been left in limbo (#468 & #408).

P.S. Thanks for all your hard work on React & Redux.  It's made my life incredibly better both in working on web applications and in mentoring and training others.  The effort you put into documentation & tooling means everything.

**Comment by tkirda** [comment]
I don't see why it should be marked as deprecated. Usage shows more than 50K downloads per month. More than double over fixed-data-table-2. It is stable and works well (at least for us). Maybe there are cases where it is not sufficient and then you can freely choose to use other packages.

And with new version of react that is coming out soon, I trust it will get necessary updates and we can continue using it. We use it on a project with a very large code base and switching to something else would be time consuming and risky. Deprecating would just be not fare to current user base.

These rants about deprecation is just noise and not really helping anyone.

**Comment by wcjordan** [comment]
The issue is that there have been 5 commits since November 2015 (8 if you include merge commits).  Many users have filed issues and pull requests against the repo, and there are no active maintainers to address them.

**Comment by tkirda** [comment]
I know this is not ideal but that is reality. Low number of changes and popularity also shows that it is good enough.

**Comment by kyldvs** [comment]
@gaearon: Yes I asked @pieterv to publish a new version, should happen this morning. I don't actually have npm access for the project :)

Re: Deprecation/no active maintainers: We are aware and have been discussing it internally for a long time. Right now I do not have any updates related to that.

**Comment by wcjordan** [comment]
Thanks for the update, Kyle.  Please let me know if there's anything we can do from the FDT2 end to help with the issues around maintenance.

**Comment by kyldvs** [comment]
Looks like it should be at 0.6.4 now, thanks @pieterv :)

https://www.npmjs.com/package/fixed-data-table

**Comment by pieterv** [comment]
let me know if i broke anything :D

**Comment by gaearon** [comment]
Thanks!

**Comment by travi** [comment]
thank you for getting this pushed through!

**Comment by travi** [comment]
could we get #488 pushed through too for the `React.createClass` warnings?

**Pull request merged**
