### PR TITLE
Separate theming from functionality

### PR DESCRIPTION
**Pull request by Andreyco**
Solves issue #113

### CODE REVIEW

**Comment by pieterv** [comment]
Hey @Andreyco, Sorry for the slow response. This PR looks really good! Ill get @jbonta to give it a full review soon. Also I can take a look at the build step stuff if you wanna remove it from this PR.

Thanks for putting this together!

**Comment by Andreyco** [comment]
I will try to review stylesheets before @jbonta so that he catches up on "final" PR from my side. Wait a day or two please :)

**Comment by pieterv** [comment]
@jbonta how do you feel about having all the theme styles in a single file? Is it worth splitting them out?

**Comment by jbonta** [comment]
I think it's fine as-is in a single theme stylesheet. Will wait for the '.public/' prefixing from @Andreyco . Thanks!

**Comment by Andreyco** [comment]
I think renaming should happen in `src/theme/default.css` and in files located at `src/css/` (where needed), or are you going to add `public_` prefixed classes to markup?

Originally I submitted this PR in order to split style to 2 files.
- main file: required to get FDT working (positioning, border widths, ...)
- theming file: visual styling (border colors, backgrounds, ...)
Having this file structure devs could just not include theming file and introduce their own theming file without using `!important` to override styles (in some cases).

**Comment by ehzhang** [comment]
@Andreyco thanks for the PR! It's been merged in with a few changes.

**Pull request merged**
