### PR TITLE
v0.6 API Transition Release

### PR DESCRIPTION
**Pull request by pieterv**
This is the code in #221 but rebased against master + the following changes:
- Sync latest changes from FB
- Updated readme
- Updated examples

This code will be released as `0.6.0-rc1` after merging.

### CODE REVIEW

**Comment by pieterv** [comment]
cc @ehzhang @wlis

**Comment by ehzhang** [comment]
Thanks for the rebase and the perf fixes!

**Comment by pieterv** [comment]
No worries :) I simplified the examples a bunch to :)

Will be great to finally release your awesome work!

**Comment by ehzhang** [comment]
:tada: :tada: :tada:

**Comment by pieterv** [comment]
:dancers::dancers::dancers:

**Comment by pieterv** [comment]
This code has been released as [`v0.6.0-rc1`](https://github.com/facebook/fixed-data-table/releases/tag/v0.6.0-rc1)! Im working on docs now for the full release.

**Pull request merged**
