### PR TITLE
Support stateful cells by using keys

### PR DESCRIPTION
**Pull request by marcneuwirth**
This will pass through the key, if used, so that stateful cells are possible.

### CODE REVIEW

**Comment by pieterv** [comment]
Im not sure i understand this change, could you give some more detailed information on what the current behavior is on render and what this effect this change will have?

**Comment by marcneuwirth** [comment]
If you define custom components to be rendered with `cellRenderer`, it is not possible to set a `key` prop on that component, because it is not passed through `cloneWithProps`. That means that the table will reuse the same component and just change the `props`. For most circumstances that is great, unless you want to use `state`. 

Normally in this situation, I would use a `key` prop so that React would know when to reuse the same component vs create a new one. In this case, things that I expect would happen when a new row is rendered, like `componentWillMount ` and `getInitialState`, are never called again because the component is being reused. Using `cloneWithProps` is removing functionality, and without my knowledge, so that looking through the code is the only way to figure out why this isn't working.

With this change, components created by `cellRenderer` will still behave the same way by default if no `key` is used. This only allows the possibility of passing through a `key` and behaving how you would expect.

**Comment by pieterv** [comment]
@marcneuwirth Nice, yes this makes sense! Thanks for the detailed explanation. This should also be fixed when we move to the `React.cloneElement` API instead of `cloneWithProps` but this is a good interim solution.

**Comment by marcneuwirth** [comment]
:beers:

**Pull request merged**
