### PR TITLE
right-fixed column imlementation

### PR DESCRIPTION
**Pull request by u9520107**
Happens to need to fix some columns at the right of the table.

### CODE REVIEW

**Comment by altaihero** [comment]
+1

**Comment by tsemerad** [comment]
+1

**Comment by u9520107** [comment]
This is already outdated. Not sure when I'll have to time to work on this though.

**Comment by prateekjahead** [comment]
Had to use react-virtualized due to this lacking feature. So +1.

**Comment by somonek** [comment]
+1

**Comment by u9520107** [comment]
not sure if it is still relevant...

**Pull request closed without merging**
