### PR TITLE
Fix #81 - Vertical scrollbar overlays header

### LINKED ISSUE #81: Vertical scrollbar overlays header row(s)
The vertical table scrollbar overlays the header row(s) of the table, as can be seen in the examples. This seems like a bug since the scrollable area is the set of rows below the header row(s). I don't think this is a huge deal, but it can be misleading for some users.

Since `headerHeight` is a required property for `Table`, it seems that it would be possible to set the area of the vertical scrollbar to the rows beneath the header. If I have time, and this is indeed considered a bug, I can work on a PR.

Thanks for everybody's hard work on this library. I've been having great success using it for our team's various needs. Great work!

### PR DESCRIPTION
**Pull request by mikestead**
#81 
I'm not too sure if this is something you think needs fixing but it was causing us a little grief by obscuring the sort arrow in the right hand columns header.

Feels a little better keeping the scrollbar inside the body of the table to my eye. Let me know what you think.

### CODE REVIEW

**Comment by pieterv** [comment]
Hey @mikestead Thanks for the PR!

@jbonta @wlis What do you think about changing the scroll bar to not overlap the header?

**Comment by jbonta** [comment]
yeah, I think this makes sense. Does the header's shadow still cover the scrollbar? Do you have a screenshot? cc @wlis

**Comment by mikestead** [comment]
@jbonta good point, the scroll bar track is sitting on top of the header shadow which looks off.

The Scrollbar z-index defaults to 99 in the component, but it can be passed a different z-index prop to use. The shadow z-index is defined in the css file. I can bump that up to 100 (see before / after images below) but not sure that's a great fix.

screen shot 2015-05-21 at 2 31 39 pm
=======
screen shot 2015-05-21 at 2 32 04 pm

**Comment by ehzhang** [comment]
Thanks for the PR! It's been merged in, with the adjustment to the z-index (100).

**Pull request merged**
