### PR TITLE
[RFC] v0.5 API Transition Release

### PR DESCRIPTION
**Pull request by ehzhang**
Follows #207 

With the major changes outlined below, this transition release provides the previous functionality witha mapping layer while also allowing the user to use the new API if chosen.

**DO NOT MERGE** (yet)

Lots of changes here! I'm requesting some comments both from our team and the community, and also just presenting the current state of this API transition. This is still a work in progress, and may still have some changes to be made and other bits and pieces cleaned up.

Most notably, this release deprecates the *Getter and *Renderer functions to be replaced simply with `cell`, `header`, and `footer`, which take in React components or strings.

### But why?

Fixed Data Table, as we state in the readme, is about handling **large** amounts of data, but most importantly about performant scrolling and row virtualization. The way of fetching the data itself is not a main concern - we just care about making sure that whatever content you give it renders quickly.

#### Kill Getter <-> Renderer data dependencies
Well, asides from the basic case where we need to render simple, text data, the fact that the renderer functions relied on data from getters to trigger renders makes it a bit tricky to manage the UI at the cell level because of this data dependency. Sometimes we need to build much more complicated UI components at the cell level, and working with these data dependencies leads to yuckier code.

#### Components, not renderers.
Cells will take care of fetching the data they need, **not** the table. And users must think about creating React components instead of renderers. We're taking advantage of a more React-like way of thinking to make this a bit more modular. Only cells would really need to be components though - You can still keep your header and footer by just passing in a string to the Column prop `header` and `footer` respectively for the basic default header or footer. This replaces the `label` prop. If you really wanted to, you could also pass in a string to the to the `cell` prop - but that would just render the same string for all the cells, so, yeah.

#### Increased flexibility, styling
Since we'll be using components for cells, passing in a component means that you get to to apply the props that you want, where you want them. You're not limited just to the `dataKey` prop - add whatever you feel! Call it `batman` if you want, you're the king here. This also means that props like `onClick` or `onDoubleClick` apply here too. We provide a basic `<Cell>` component you can use to get the basic vertically-aligned and padded table cell, but if you don't want to use that, you don't have to!

### This seems scary!

Yes, this would deprecate extremely large portions of the API - however, we will likely be creating an intermediate release that will give you an opportunity to still use the API as it is right now, but with warnings. Otherwise, if this severely breaks your workflow, you can always use v0.4.x.

#### Summary of changes:
DEPRECATE:
- columnData
- footerData
- header/footer/cellDataGetter
- header/cell/footerRenderer
- header/cell/footer/ClassName
- dataKey

ADD:
- Column props:
- header: String or element
- cell: String or element
- footer: String or element
- columnKey: Optional identifier for resizing

cc @pieterv @jbonta @hedgerwang @wlis

### CODE REVIEW

**Comment by wlis** [comment]
That looks cool. I went very quickly over and I see that you are still using ReactComponentWithPureRenderMixin in Cells/Rows. With that and no data there is no way for user to force the table to render new contents for cells. I don't think we can assume that everyone who uses table has cells subscribing to data sources and is ok with not re-rendering cells. At this point the FixedDataTableCell.react with the set of props will nearly always return false from shouldComponentUpdate.

**Comment by cesarandreu** [comment]
Awesome, the new API looks a lot nicer. Have you done any benchmarks that you could share?

Would you consider publishing it as `0.5.0-alpha.0` or similar on npm so it's easier to try out?

Having an intermediate release that lets you use both APIs would be a really nice touch, it lets you avoid having to convert all your tables at once, which can be annoying.

**Comment by weixing2014** [comment]
Hi, Edwin,

This is so great! We have been keeping eyes on this project for a long time and are happily to see this transition by which the table could be more flexible and easy to customize. 

One thing I'm curious is whether your changes will make reordering columns easier if we want to implement this feature by ourselves? According to your write-up I feel the answer should be "Yes" while I'm not 100% sure. 

Thanks!

**Comment by ehzhang** [comment]
Hey @weixing2014, the method of reordering columns would not change with this release - in order to reorder columns, you will need to implement your own logic to pass in the re-organized columns under the `<Table>` Component.

**Comment by weixing2014** [comment]
@ehzhang thanks!

**Comment by brynjargr** [comment]
Hello @ehzhang, we are interested in using FixedDataTables for a project that we are going to start soon, but we don't want to start with version 0.4 knowing that 0.5 is coming soon. Do you have any estimate for when this will be merged and 0.5 will be released?

**Comment by yrokhlin** [comment]
I too would love to know the answer to this question +1

**Comment by puzzfuzz** [comment]
+1 These changes look great. I've run into a lot of the same issues others have mentioned around updating cell or header contents (sorting columns, adjusting rendered date-range for tabular data, etc.) Any update on when we can expect to see 0.5 shipping?

**Comment by jasongonzales23** [comment]
What's going on with 0.5?? It looks like this release will fix the major issue I am facing!

**Comment by Chehai** [comment]
I understand that 0.5 is still in development, but I do notice a performance issue in the api-v0.5 branch which I believe will be the future 0.5 release.

To reproduce the performance issue, you can use your phone to access the JSON data example in the api-v0.5 branch and do some scrolling. This example is much slower than the same example in the master branch.

https://github.com/facebook/fixed-data-table/blob/api-v0.5/src/FixedDataTable.react.js#L640 is the problem. It compares column definitions between a table's new props and old state. Since `<Column />` can take `<Cell />` as a prop and `<Cell />` can be translated to `React.createElement`, column definitions of the table's new props will always be different from the old state. As a result, whole table rendering happens very often and scrolling is very slow.

**Comment by yrokhlin** [comment]
Hey why is this closed? Is this ever going to be released?? I know we are on v0.5 NOW but all it does is add some compatibility with 0.14 while breaking everything else (laggiest release to date.) None of the changes we really need, like the new API, has made it over. No one will answer why, or what the hell is going on, and @ehzhang seems to have closed this issue, with out any comment as to wtf is going on.

The current state of F-D-D is terrible, and I can't believe a multi-billion dollar company such as Facebook would leave a public facing product this way.

**Comment by ehzhang** [comment]
@yrokhlin - I was just about to make a comment regarding this.

The current state of this PR is incompatible with the current v0.5.0 with the new React support for 0.14, and is also incomplete in a few other places regarding performance. A version similar to this may be released soon, but not in this specific PR.

I closed this mostly to clean up the list of PRs. @wlis or @pieterv will be better able to answer questions regarding the state of the table source.

As an added note, I do not speak on behalf of Facebook with regards to the state of this project.

**Comment by brynjargr** [comment]
@ehzhang thank you for your comment, it gives us hope that a version similar to this may be released. But is there any chance you or @pieterv or whoever can speak on behalf of Facebook can give us a more committal answer than "may be released soon"?
We have started a project based off of this version of the API since we did not like the previous version as much. Of course we knew that was a risk since this had not been merged. But now that this has been closed and there is no commitment from Facebook to make this change to the API within any period of time that leaves us in a difficult spot. Please help us out a little bit. You had done a great job making these API changes and we would really like to see these changes make their way to a released version.

**Comment by brynjargr** [comment]
Also, I'm sure that Facebook, like all of us, has a lot of things that they can spend their time working on. So if this is not a priority, then can you at least tell us if you would be open to merging a pull request from us or someone else with changes similar to this one. That would help us decide if we should spend our time addressing the incompatibilities and incompleteness that @ehzhang mentions above.

**Pull request closed without merging**
