### PR TITLE
Support AMD, CJS and browser global environments

### LINKED ISSUE #78: UMD/AMD support?
I can't use gulp/grunt processing and I don't want to load fixed-data-table and React as global objects. Id' like to load the library as AMD (or UMD) module. The problem is, files generated in dist/* by Webpack are not UMD/AMD compatible :(

### PR DESCRIPTION
**Pull request by pieterv**
Fixes #78, #18

### CODE REVIEW

**Comment by hipertracker** [comment]
You forgot to rebuild dist/ based on new UMD format.

Why webpack.config has 

```
  externals: {
    react: 'React'
  },
```

The standard convention in AMD is using lowercase ('react', not 'React') (and it is required by other libs, eg. `requirejs-babel`). Because of that, I have to [import React twice](https://github.com/hipertracker/react-embed/blob/master/requirejs.config.js#L9-L10)  Any suggestions?

**Comment by pieterv** [comment]
@hipertracker I will build the dist files when we release. As for the `React` i had it that way was the browser global for react is `window.React` not lowercase but ill look for a way to support both. Thanks for the feedback!

**Comment by pieterv** [comment]
@hipertracker after some sleuthing around other webpack configs i think have the solution now. If you could try the new changes that would be very helpful :)

**Comment by hipertracker** [comment]
@pieterv now all works like a charm :) I only needed to rebuild dis/*

**Comment by pieterv** [comment]
Nice! Thanks for testing.

**Pull request merged**
