### PR TITLE
Add onRowContextMenu callback

### PR DESCRIPTION
**Pull request by difelice**
## Feature
Add more **Table** event callbacks.
### Tasks
- [x] onRowContextMenu

### CODE REVIEW

**Comment by wlis** [comment]
@difelice Thanks for writing the pull request! I would like to take the change for onRowContextMenu, but there are a bit to many changes here and automatic merge will not work. Could you please request the change for onRowContextMenu only within 1 commit?

**Comment by difelice** [comment]
Sure thing.

**Comment by difelice** [comment]
Moved to a new PR https://github.com/facebook/fixed-data-table/pull/160

**Comment by difelice** [comment]
@wlis PR https://github.com/facebook/fixed-data-table/pull/160 should be ok to merge.

Thanks for adding this feature!

**Pull request closed without merging**
