### PR TITLE
Don't pass columnKey prop to div element

### LINKED ISSUE #420: Warning: Unknown prop `columnKey` when there is no columnKey prop
Hi, I'm using Fixed Data Table for 2 weeks now and today I added a class on the cell to be able to get the cell content in some unit tests. Since I added that class property to <Cell> I'm keep getting this Warning either I remove the class or not.

> Warning: Unknown prop `columnKey` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by FixedDataTableCellDefault)
>     in FixedDataTableCellDefault (created by VNF Table)
>     in div (created by FixedDataTableCell)
>     in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
>     in div (created by FixedDataTableCellGroupImpl)
>     in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
>     in div (created by FixedDataTableCellGroup)
>     in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
>     in div (created by FixedDataTableRowImpl)
>     in div (created by FixedDataTableRowImpl)
>     in FixedDataTableRowImpl (created by FixedDataTableRow)
>     in div (created by FixedDataTableRow)
>     in FixedDataTableRow (created by FixedDataTable)
>     in div (created by FixedDataTable)
>     in div (created by FixedDataTable)
>     in FixedDataTable (created by TransitionTable)
>     in TransitionTable (created by VNF Table)
>     in div (created by VNF Table)

**Cell Component:**

```javascript
const TextCell = ({rowIndex, data, col}) => (
  <Cell className = {col + '-' + rowIndex} >
    { data.getObjectAt(rowIndex)[col] }
  </Cell>
);

```
**Chrome debugger:**

> ...
> className: "fixedDataTableCellLayout_wrap1 public_fixedDataTableCell_wrap1"
> columnKey: undefined
> ...

Any ideas how can I fix it?

### PR DESCRIPTION
**Pull request by Dilatorily**
See: https://facebook.github.io/react/warnings/unknown-prop.html

Fixes #420

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by KamranAsif** [comment]
Hey,

We have this fix in our repo: https://github.com/schrodinger/fixed-data-table-2/pull/28
I haven't seen much support for this repo so we've went ahead and created a maintained fork. Feel free to check it out

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
Thanks!

**Comment by zpao** [comment]
Just shipped 0.6.2 with this.

**Pull request merged**
