### PR TITLE
onRowContextMenu Callback

### PR DESCRIPTION
**Pull request by difelice**
- [x] Add onRowContextMenu to Table

### CODE REVIEW

**Comment by ehzhang** [comment]
@difelice thanks for the pull request!

I'll batch this into the next v0.4.x release. However, v0.5.0 (for the future #193) will be focused on removing these Table level API additions in favor of defining your own row components with your own props.

**Comment by khankuan** [comment]
Will this be merged in soon?

**Comment by ripitrust** [comment]
Would like to know if this is still available 
since I didn't see it in the code

**Comment by luin** [comment]
+1 for the context menu. Any workaround before we have this shipped?

**Comment by difelice** [comment]
@luin you probably have to handle it at the cellRenderer level

**Comment by difelice** [comment]
This must be ported to the new API.

**Comment by luin** [comment]
@difelice Just tested this pull request with 0.5.0, and it worked great. Seems we can just merge this pr without port it to the new API. Did I miss something?

**Comment by ripitrust** [comment]
this looks great

I am looking into how to do it in v0.6

**Comment by difelice** [comment]
I reopened the PR, the callback is at the *Row* level and seems not to be affected by the new API (Cell, etc.). However this will soon be part of a Row component API on the roadmap.

I also have a one-commit branch.

Thanks.

**Comment by difelice** [comment]
Moved to: https://github.com/facebook/fixed-data-table/pull/321

**Pull request closed without merging**
