### PR TITLE
react-tools -> babel <3

### PR DESCRIPTION
**Pull request by pieterv**
Swap out the use of `react-tools` for `babel`. The main reason for doing this is the way `babel` polyfills at a library level rather than needing it globally, meaning you won't need anyone to change anything about your environment to use fixed-data-table.

This solves the common `Object.assign` doesn't exist issue.

### CODE REVIEW

**Comment by pieterv** [comment]
@JedWatson Im using your babel-plugin-object-assign project here :) Unfortunately i couldn't use the project as a dependency as it was giving me an error about using two different instances of Babel, i think your project might need to use peerDeps to solve this but not sure. Anyway thanks for creating this!

**Comment by franleplant** [comment]
Love this! Waiting for it!

**Comment by ifrit** [comment]
Any progress on merging this? We're some ES6/babel users eagerly waiting to use it.

**Comment by pieterv** [comment]
@ifrit :) I have merged it in, we are aiming to do the release next week.

**Comment by ifrit** [comment]
Excellent news! thanks @pieterv!

**Comment by JedWatson** [comment]
@pieterv glad to hear it! sorry I missed the first notification - let me know if you're still having issues, I've been working to try and resolve the two-babels problem (and a couple of others) recently.

**Comment by cesarandreu** [comment]
@pieterv any update on doing a release with this :)?

**Comment by ifrit** [comment]
Yeah, that would be great. I tried pulling it from github directly and running the build scripts but couldn't get it to render properly.

**Comment by zackify** [comment]
Same, I need this!

**Comment by pieterv** [comment]
Hey @cesarandreu, @ifrit, @zackify sorry for the delay but we have now done the v0.2.0 release, with this code in it! Check it out, and please let us know if something doesnt work for you :)

**Comment by cesarandreu** [comment]
Awesome, thanks @pieterv! Seems to be working.

**Pull request merged**
